use_nerf :  True
use_gen  : True
use_face :  True
#use_face :  False

model : P_vrnr
use_nerf_time_latent : True
is_expand_nerf_channel : True
is_insert_nerf_depth : True
fuse_mode  : 0
nerf_output_rgb_dim : 256
is_skip_nerf : True

uv_reso: 128